"""ISO3 -> (UN M49 code, display name) mapping.

Source: UN Population Division Data Portal, 2024.
"""

COUNTRY_CODES: dict[str, tuple[int, str]] = {
    "ABW": (533, "Aruba"),
    "AFG": (4, "Afghanistan"),
    "AGO": (24, "Angola"),
    "AIA": (660, "Anguilla"),
    "ALB": (8, "Albania"),
    "AND": (20, "Andorra"),
    "ANT": (530, "Netherlands Antilles"),
    "ARE": (784, "United Arab Emirates"),
    "ARG": (32, "Argentina"),
    "ARM": (51, "Armenia"),
    "ASM": (16, "American Samoa"),
    "ATG": (28, "Antigua and Barbuda"),
    "AUS": (36, "Australia"),
    "AUT": (40, "Austria"),
    "AZE": (31, "Azerbaijan"),
    "BDI": (108, "Burundi"),
    "BEL": (56, "Belgium"),
    "BEN": (204, "Benin"),
    "BES": (535, "Bonaire, Sint Eustatius and Saba"),
    "BFA": (854, "Burkina Faso"),
    "BGD": (50, "Bangladesh"),
    "BGR": (100, "Bulgaria"),
    "BHR": (48, "Bahrain"),
    "BHS": (44, "Bahamas"),
    "BIH": (70, "Bosnia and Herzegovina"),
    "BLR": (112, "Belarus"),
    "BLZ": (84, "Belize"),
    "BMU": (60, "Bermuda"),
    "BOL": (68, "Bolivia"),
    "BRA": (76, "Brazil"),
    "BRB": (52, "Barbados"),
    "BRN": (96, "Brunei Darussalam"),
    "BTN": (64, "Bhutan"),
    "BWA": (72, "Botswana"),
    "CAF": (140, "Central African Republic"),
    "CAN": (124, "Canada"),
    "CHE": (756, "Switzerland"),
    "CHL": (152, "Chile"),
    "CHN": (156, "China"),
    "CIV": (384, "Cote d'Ivoire"),
    "CMR": (120, "Cameroon"),
    "COD": (180, "DR Congo"),
    "COG": (178, "Congo"),
    "COK": (184, "Cook Islands"),
    "COL": (170, "Colombia"),
    "COM": (174, "Comoros"),
    "CPV": (132, "Cabo Verde"),
    "CRI": (188, "Costa Rica"),
    "CUB": (192, "Cuba"),
    "CUW": (531, "Curacao"),
    "CYM": (136, "Cayman Islands"),
    "CYP": (196, "Cyprus"),
    "CZE": (203, "Czechia"),
    "DEU": (276, "Germany"),
    "DJI": (262, "Djibouti"),
    "DMA": (212, "Dominica"),
    "DNK": (208, "Denmark"),
    "DOM": (214, "Dominican Republic"),
    "DZA": (12, "Algeria"),
    "ECU": (218, "Ecuador"),
    "EGY": (818, "Egypt"),
    "ERI": (232, "Eritrea"),
    "ESP": (724, "Spain"),
    "EST": (233, "Estonia"),
    "ETH": (231, "Ethiopia"),
    "EUR": (908, "Europe"),
    "FIN": (246, "Finland"),
    "FJI": (242, "Fiji"),
    "FLK": (238, "Falkland Islands"),
    "FRA": (250, "France"),
    "FRO": (234, "Faroe Islands"),
    "FSM": (583, "Micronesia"),
    "GAB": (266, "Gabon"),
    "GBR": (826, "United Kingdom"),
    "GEO": (268, "Georgia"),
    "GHA": (288, "Ghana"),
    "GIB": (292, "Gibraltar"),
    "GIN": (324, "Guinea"),
    "GLP": (312, "Guadeloupe"),
    "GMB": (270, "Gambia"),
    "GNB": (624, "Guinea-Bissau"),
    "GNQ": (226, "Equatorial Guinea"),
    "GRC": (300, "Greece"),
    "GRD": (308, "Grenada"),
    "GRL": (304, "Greenland"),
    "GTM": (320, "Guatemala"),
    "GUF": (254, "French Guiana"),
    "GUM": (316, "Guam"),
    "GUY": (328, "Guyana"),
    "HKG": (344, "China, Hong Kong SAR"),
    "HND": (340, "Honduras"),
    "HRV": (191, "Croatia"),
    "HTI": (332, "Haiti"),
    "HUN": (348, "Hungary"),
    "IDN": (360, "Indonesia"),
    "IND": (356, "India"),
    "IRL": (372, "Ireland"),
    "IRN": (364, "Iran"),
    "IRQ": (368, "Iraq"),
    "ISL": (352, "Iceland"),
    "ISR": (376, "Israel"),
    "ITA": (380, "Italy"),
    "JAM": (388, "Jamaica"),
    "JOR": (400, "Jordan"),
    "JPN": (392, "Japan"),
    "KAZ": (398, "Kazakhstan"),
    "KEN": (404, "Kenya"),
    "KGZ": (417, "Kyrgyzstan"),
    "KHM": (116, "Cambodia"),
    "KIR": (296, "Kiribati"),
    "KNA": (659, "Saint Kitts and Nevis"),
    "KOR": (410, "Republic of Korea"),
    "KWT": (414, "Kuwait"),
    "LAO": (418, "Lao PDR"),
    "LBN": (422, "Lebanon"),
    "LBR": (430, "Liberia"),
    "LBY": (434, "Libya"),
    "LCA": (662, "Saint Lucia"),
    "LIE": (438, "Liechtenstein"),
    "LKA": (144, "Sri Lanka"),
    "LSO": (426, "Lesotho"),
    "LTU": (440, "Lithuania"),
    "LUX": (442, "Luxembourg"),
    "LVA": (428, "Latvia"),
    "MAC": (446, "China, Macao SAR"),
    "MAR": (504, "Morocco"),
    "MCO": (492, "Monaco"),
    "MDA": (498, "Moldova"),
    "MDG": (450, "Madagascar"),
    "MDV": (462, "Maldives"),
    "MEX": (484, "Mexico"),
    "MHL": (584, "Marshall Islands"),
    "MKD": (807, "North Macedonia"),
    "MLI": (466, "Mali"),
    "MLT": (470, "Malta"),
    "MMR": (104, "Myanmar"),
    "MNE": (499, "Montenegro"),
    "MNG": (496, "Mongolia"),
    "MOZ": (508, "Mozambique"),
    "MRT": (478, "Mauritania"),
    "MSR": (500, "Montserrat"),
    "MTQ": (474, "Martinique"),
    "MUS": (480, "Mauritius"),
    "MWI": (454, "Malawi"),
    "MYS": (458, "Malaysia"),
    "MYT": (175, "Mayotte"),
    "NAM": (516, "Namibia"),
    "NCL": (540, "New Caledonia"),
    "NER": (562, "Niger"),
    "NGA": (566, "Nigeria"),
    "NIC": (558, "Nicaragua"),
    "NIU": (570, "Niue"),
    "NLD": (528, "Netherlands"),
    "NOR": (578, "Norway"),
    "NPL": (524, "Nepal"),
    "NRU": (520, "Nauru"),
    "NZL": (554, "New Zealand"),
    "OMN": (512, "Oman"),
    "PAK": (586, "Pakistan"),
    "PAN": (591, "Panama"),
    "PER": (604, "Peru"),
    "PHL": (608, "Philippines"),
    "PLW": (585, "Palau"),
    "PNG": (598, "Papua New Guinea"),
    "POL": (616, "Poland"),
    "PRI": (630, "Puerto Rico"),
    "PRK": (408, "North Korea"),
    "PRT": (620, "Portugal"),
    "PRY": (600, "Paraguay"),
    "PSE": (275, "State of Palestine"),
    "PYF": (258, "French Polynesia"),
    "QAT": (634, "Qatar"),
    "REU": (638, "Reunion"),
    "ROU": (642, "Romania"),
    "RUS": (643, "Russian Federation"),
    "RWA": (646, "Rwanda"),
    "SAU": (682, "Saudi Arabia"),
    "SDN": (729, "Sudan"),
    "SEN": (686, "Senegal"),
    "SGP": (702, "Singapore"),
    "SHN": (654, "Saint Helena"),
    "SLB": (90, "Solomon Islands"),
    "SLE": (694, "Sierra Leone"),
    "SLV": (222, "El Salvador"),
    "SMR": (674, "San Marino"),
    "SOM": (706, "Somalia"),
    "SRB": (688, "Serbia"),
    "SSD": (728, "South Sudan"),
    "STP": (678, "Sao Tome and Principe"),
    "SUR": (740, "Suriname"),
    "SVK": (703, "Slovakia"),
    "SVN": (705, "Slovenia"),
    "SWE": (752, "Sweden"),
    "SWZ": (748, "Eswatini"),
    "SXM": (534, "Sint Maarten"),
    "SYC": (690, "Seychelles"),
    "SYR": (760, "Syria"),
    "TCA": (796, "Turks and Caicos Islands"),
    "TCD": (148, "Chad"),
    "TGO": (768, "Togo"),
    "THA": (764, "Thailand"),
    "TJK": (762, "Tajikistan"),
    "TKL": (772, "Tokelau"),
    "TKM": (795, "Turkmenistan"),
    "TLS": (626, "Timor-Leste"),
    "TON": (776, "Tonga"),
    "TTO": (780, "Trinidad and Tobago"),
    "TUN": (788, "Tunisia"),
    "TUR": (792, "Turkiye"),
    "TUV": (798, "Tuvalu"),
    "TWN": (158, "China, Taiwan"),
    "TZA": (834, "Tanzania"),
    "UGA": (800, "Uganda"),
    "UKR": (804, "Ukraine"),
    "URY": (858, "Uruguay"),
    "USA": (840, "United States of America"),
    "UZB": (860, "Uzbekistan"),
    "VCT": (670, "Saint Vincent and the Grenadines"),
    "VEN": (862, "Venezuela"),
    "VGB": (92, "British Virgin Islands"),
    "VIR": (850, "US Virgin Islands"),
    "VNM": (704, "Viet Nam"),
    "VUT": (548, "Vanuatu"),
    "WLF": (876, "Wallis and Futuna Islands"),
    "WSM": (882, "Samoa"),
    "YEM": (887, "Yemen"),
    "ZAF": (710, "South Africa"),
    "ZMB": (894, "Zambia"),
    "ZWE": (716, "Zimbabwe"),
}

DISPLAY_ALIASES: dict[str, str] = {
    "KOR": "South Korea",
    "USA": "USA",
    "GBR": "UK",
    "ARE": "UAE",
    "PRK": "North Korea",
    "RUS": "Russia",
    "CHN": "China",
    "TWN": "Taiwan",
    "EUR": "Europe",
}


def resolve(query: str) -> tuple[str, int, str]:
    """Resolve a user query (ISO3, name fragment, or alias) to (iso3, m49, display_name).

    Raises ValueError if no match found.
    """
    q = query.strip().upper()
    if q in COUNTRY_CODES:
        m49, name = COUNTRY_CODES[q]
        return q, m49, DISPLAY_ALIASES.get(q, name)

    q_lower = query.strip().lower()
    for iso3, (m49, name) in COUNTRY_CODES.items():
        if q_lower == name.lower():
            return iso3, m49, DISPLAY_ALIASES.get(iso3, name)

    for alias, iso3_alias in {v.lower(): k for k, v in DISPLAY_ALIASES.items()}.items():
        if q_lower == alias:
            m49, name = COUNTRY_CODES[iso3_alias]
            return iso3_alias, m49, DISPLAY_ALIASES.get(iso3_alias, name)

    for iso3, (m49, name) in COUNTRY_CODES.items():
        if q_lower in name.lower():
            return iso3, m49, DISPLAY_ALIASES.get(iso3, name)

    raise ValueError(f"Unknown country: '{query}'. Use ISO3 code (e.g. KOR, FRA, JPN) or country name.")
